/*
 * This file is generated by jOOQ.
 */
package sf.otp.dao.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import sf.otp.dao.jooq.tables.User;


/**
 * A class modelling indexes of tables in otp.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UNIQUE_ADMIN_USER = Internal.createIndex(DSL.name("unique_admin_user"), User.USER, new OrderField[] { User.USER.ROLE }, true);
}
