/*
 * This file is generated by jOOQ.
 */
package sf.otp.dao.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sf.otp.dao.jooq.tables.Config;
import sf.otp.dao.jooq.tables.Token;
import sf.otp.dao.jooq.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Otp extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>otp</code>
     */
    public static final Otp OTP = new Otp();

    /**
     * Таблица с настройками для otp
     */
    public final Config CONFIG = Config.CONFIG;

    /**
     * Таблица для хранения токенов
     */
    public final Token TOKEN = Token.TOKEN;

    /**
     * Пользователи
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Otp() {
        super("otp", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Config.CONFIG,
            Token.TOKEN,
            User.USER
        );
    }
}
