/*
 * This file is generated by jOOQ.
 */
package sf.otp.dao.jooq;


import sf.otp.dao.jooq.tables.Config;
import sf.otp.dao.jooq.tables.Token;
import sf.otp.dao.jooq.tables.User;


/**
 * Convenience access to all tables in otp.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Таблица с настройками для otp
     */
    public static final Config CONFIG = Config.CONFIG;

    /**
     * Таблица для хранения токенов
     */
    public static final Token TOKEN = Token.TOKEN;

    /**
     * Пользователи
     */
    public static final User USER = User.USER;
}
